if("serviceWorker"in navigator){addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const $=id=>document.getElementById(id);
const st={tool:"move",sel:null,icons:[],draw:[],texts:[],checked:{},pdf:null,page:1,pages:0,w:0,h:0,scale:1,tx:0,ty:0,pts:new Map(),pan:null,pinch:null,drawing:false,stroke:null,appZoom:1,photoSeq:1,down:null};
$("date").value=new Date().toISOString().slice(0,10);
function data(){return{v:"6",bridge:$("bridge").value,route:$("route").value,date:$("date").value,person:$("person").value,folder:$("folder").value,clientId:$("clientId").value,icons:st.icons,draw:st.draw,texts:st.texts,checked:st.checked,appZoom:st.appZoom,photoSeq:st.photoSeq}}
function save(){localStorage.setItem("fieldbook_v6",JSON.stringify(data()))}
function safe(s){return String(s||"").replace(/[\\/:*?"<>| \u3000]/g,"_")}
["bridge","route","date","person","folder","clientId"].forEach(id=>$(id).onchange=save);
function setTool(t){st.tool=t;document.querySelectorAll(".tool").forEach(b=>b.classList.remove("active"));$(t).classList.add("active");$("ink").style.pointerEvents=(["pen","marker","eraser"].includes(t))?"auto":"none"}
["move","photoIcon","pen","marker","text","eraser"].forEach(id=>$(id).onclick=()=>setTool(id));
$("appZoomIn").onclick=()=>{st.appZoom=Math.min(1.5,st.appZoom+.1);$("appMain").style.transform=`scale(${st.appZoom})`;save()};$("appZoomOut").onclick=()=>{st.appZoom=Math.max(.75,st.appZoom-.1);$("appMain").style.transform=`scale(${st.appZoom})`;save()};
$("pdfInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;st.pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;st.pages=st.pdf.numPages;st.page=1;await renderPage();$("view").scrollIntoView({behavior:"smooth",block:"center"})};
$("prev").onclick=()=>goPage(st.page-1);$("next").onclick=()=>goPage(st.page+1);async function goPage(n){if(!st.pdf||n<1||n>st.pages)return;st.page=n;st.sel=null;await renderPage()}$("reset").onclick=()=>fit();
$("checkPage").onclick=()=>{st.checked[st.page]=!st.checked[st.page];updatePageBadge();save()};function updatePageBadge(){let c=st.checked[st.page]?" ✓チェック済":" 未チェック";$("page").textContent=st.pages?`${st.page} / ${st.pages}ページ${c}`:"PDF未読込"}
async function renderPage(){let p=await st.pdf.getPage(st.page),v0=p.getViewport({scale:1}),sc=Math.min(1.8,Math.max(1000,$("view").clientWidth*1.7)/v0.width),v=p.getViewport({scale:sc});["pdf","ink"].forEach(id=>{$(id).width=v.width;$(id).height=v.height});st.w=v.width;st.h=v.height;$("stage").style.width=v.width+"px";$("stage").style.height=v.height+"px";$("icons").style.width=v.width+"px";$("icons").style.height=v.height+"px";$("empty").style.display="none";updatePageBadge();await p.render({canvasContext:$("pdf").getContext("2d"),viewport:v}).promise;fit();renderAll()}
function fit(){let vw=$("view").clientWidth,vh=$("view").clientHeight;st.scale=Math.min(vw/st.w,vh/st.h)*.98;st.tx=(vw-st.w*st.scale)/2;st.ty=12;tf()}function tf(){$("stage").style.transform=`translate(${st.tx}px,${st.ty}px) scale(${st.scale})`}function toPdf(x,y){let r=$("view").getBoundingClientRect();return{x:(x-r.left-st.tx)/st.scale,y:(y-r.top-st.ty)/st.scale}}
$("view").onpointerdown=e=>{$("view").setPointerCapture(e.pointerId);st.pts.set(e.pointerId,{x:e.clientX,y:e.clientY});st.down={x:e.clientX,y:e.clientY,t:Date.now(),tool:st.tool};if(st.tool==="photoIcon"){addIcon(toPdf(e.clientX,e.clientY));return}if(st.tool==="text"){addText(toPdf(e.clientX,e.clientY));return}if(["pen","marker","eraser"].includes(st.tool)){startStroke(e);return}st.pan={x:e.clientX,y:e.clientY}};
$("view").onpointermove=e=>{if(!st.pts.has(e.pointerId))return;st.pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(["pen","marker","eraser"].includes(st.tool)&&st.drawing){moveStroke(e);return}if(st.tool!=="move")return;let a=[...st.pts.values()];if(a.length===1&&st.pan){st.tx+=e.clientX-st.pan.x;st.ty+=e.clientY-st.pan.y;st.pan={x:e.clientX,y:e.clientY};tf()}else if(a.length>=2){let d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),c={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};if(st.pinch){let before=toPdf(c.x,c.y);st.scale=Math.min(6,Math.max(.15,st.scale*d/st.pinch.d));let r=$("view").getBoundingClientRect();st.tx=c.x-r.left-before.x*st.scale;st.ty=c.y-r.top-before.y*st.scale;tf()}st.pinch={d,c}}};
$("view").onpointerup=$("view").onpointercancel=e=>{if(["pen","marker","eraser"].includes(st.tool)&&st.drawing)endStroke();if(st.down&&st.down.tool==="move"&&st.pts.size===1){let dx=e.clientX-st.down.x,dy=e.clientY-st.down.y,dt=Date.now()-st.down.t;if(Math.abs(dx)>120&&Math.abs(dx)>Math.abs(dy)*1.4&&dt<900)goPage(dx<0?st.page+1:st.page-1)}st.pts.delete(e.pointerId);st.pan=null;st.pinch=null;st.down=null};
function addIcon(p){if(!st.w)return alert("PDFを先に読み込んでください");let id=Date.now()+"";st.icons.push({id,no:st.icons.length+1,page:st.page,x:p.x/st.w,y:p.y/st.h,title:"",note:"",memo:"",photos:[]});select(id);renderAll();list();save()}function addText(p){let t=prompt("PDFに記入する文字");if(!t)return;st.texts.push({page:st.page,x:p.x/st.w,y:p.y/st.h,text:t,color:$("penColor").value});renderAll();save()}
function startStroke(e){let p=toPdf(e.clientX,e.clientY),size=Number($("penSize").value),color=$("penColor").value,alpha=1;if(st.tool==="marker"){color="#facc15";size=18;alpha=.35}if(st.tool==="eraser"){color="#fff";size=24;alpha=1}st.drawing=true;st.stroke={page:st.page,pts:[{x:p.x/st.w,y:p.y/st.h}],color,width:size,alpha,erase:st.tool==="eraser"}}function moveStroke(e){let p=toPdf(e.clientX,e.clientY);st.stroke.pts.push({x:p.x/st.w,y:p.y/st.h});drawInk(true)}function endStroke(){if(st.stroke&&st.stroke.pts.length>1)st.draw.push(st.stroke);st.stroke=null;st.drawing=false;drawInk();save()}
$("undo").onclick=()=>{if(st.draw.length)st.draw.pop();else if(st.texts.length)st.texts.pop();renderAll();save()};$("clearPage").onclick=()=>{if(confirm("このページの記入を削除しますか？")){st.draw=st.draw.filter(d=>d.page!==st.page);st.texts=st.texts.filter(t=>t.page!==st.page);renderAll();save()}};
function renderAll(){icons();drawInk();texts()}function icons(){let l=$("icons");l.innerHTML="";st.icons.filter(i=>i.page===st.page).forEach(i=>{let d=document.createElement("div");d.className="ico"+(i.id===st.sel?" selected":"");d.style.left=i.x*st.w+"px";d.style.top=i.y*st.h+"px";d.textContent=i.no;d.onclick=e=>{e.stopPropagation();select(i.id)};l.appendChild(d)});texts()}function texts(){let l=$("icons");l.querySelectorAll(".txt").forEach(x=>x.remove());st.texts.filter(t=>t.page===st.page).forEach(t=>{let d=document.createElement("div");d.className="txt";d.textContent=t.text;d.style.color=t.color||"#dc2626";d.style.left=t.x*st.w+"px";d.style.top=t.y*st.h+"px";l.appendChild(d)})}
function drawInk(cur=false){let c=$("ink").getContext("2d");c.clearRect(0,0,st.w,st.h);let arr=st.draw.filter(d=>d.page===st.page);if(cur&&st.stroke)arr=arr.concat([st.stroke]);arr.forEach(s=>{if(s.pts.length<2)return;c.save();c.globalAlpha=s.alpha??1;c.globalCompositeOperation=s.erase?"destination-out":"source-over";c.strokeStyle=s.color;c.lineWidth=s.width;c.lineCap="round";c.lineJoin="round";c.beginPath();c.moveTo(s.pts[0].x*st.w,s.pts[0].y*st.h);s.pts.slice(1).forEach(p=>c.lineTo(p.x*st.w,p.y*st.h));c.stroke();c.restore()})}
function current(){return st.icons.find(i=>i.id===st.sel)}function select(id){st.sel=id;let i=current();if(!i)return;$("sel").textContent=`選択中：写真アイコン${i.no}（PDF ${i.page}ページ）`;$("title").value=i.title||"";$("note").value=i.note||"";$("memo").value=i.memo||"";preview(i.photos);icons()}$("saveInfo").onclick=()=>{let i=current();if(!i)return alert("写真アイコンを選択してください");i.title=$("title").value;i.note=$("note").value;i.memo=$("memo").value;list();save();alert("保存しました")};$("delIcon").onclick=()=>{if(!st.sel)return;if(confirm("選択アイコンを削除しますか？")){st.icons=st.icons.filter(i=>i.id!==st.sel);st.icons.forEach((i,n)=>i.no=n+1);st.sel=null;["title","note","memo"].forEach(id=>$(id).value="");$("preview").innerHTML="";renderAll();list();save()}};
$("photo").onchange=async e=>{let i=current();if(!i){alert("先に写真アイコンを選択してください");return}i.title=$("title").value;i.note=$("note").value;i.memo=$("memo").value;for(let f of [...e.target.files]){let src=await resize(f);let seq=st.photoSeq++;let name=`${safe($("bridge").value||"橋梁")}_${String(seq).padStart(3,"0")}.jpg`;i.photos.push({name,src,title:i.title,note:i.note})}preview(i.photos);list();save();e.target.value=""};function resize(file){return new Promise(res=>{let r=new FileReader();r.onload=()=>{let im=new Image();im.onload=()=>{let sc=Math.min(1,1800/im.width),cv=document.createElement("canvas");cv.width=Math.round(im.width*sc);cv.height=Math.round(im.height*sc);cv.getContext("2d").drawImage(im,0,0,cv.width,cv.height);res(cv.toDataURL("image/jpeg",.86))};im.src=r.result};r.readAsDataURL(file)})}function preview(ps){let a=$("preview");a.innerHTML="";ps.forEach((p,n)=>{let b=document.createElement("div");b.className="photoBox";b.innerHTML=`<img src="${p.src}"><span>${esc(p.name||"写真"+(n+1))}</span>`;a.appendChild(b)})}
function folderName(){return safe($("folder").value||$("bridge").value||"橋梁写真")}function list(){let a=$("list");if(!st.icons.length){a.innerHTML='<p class="note">まだ記録がありません。</p>';return}a.innerHTML="";st.icons.forEach(i=>{let d=document.createElement("div");d.className="rec";d.innerHTML=`<b>写真アイコン${i.no}：${esc(i.title||"見出し未入力")}</b><br><small>PDF:${i.page} 写真:${i.photos.length}枚 保存先:${esc(folderName())}</small><p>${esc(i.memo||"")}</p><div class="thumbs"></div>`;let th=d.querySelector(".thumbs");i.photos.forEach(p=>{let im=document.createElement("img");im.src=p.src;th.appendChild(im)});d.onclick=()=>select(i.id);a.appendChild(d)})}
$("csvBtn").onclick=()=>{let rows=[["橋梁名","路線名","点検日","点検者","PDFページ","アイコン番号","写真見出し","備考","メモ","OneDriveフォルダ","写真名","X","Y"]];st.icons.forEach(i=>rows.push([$("bridge").value,$("route").value,$("date").value,$("person").value,i.page,i.no,i.title,i.note,i.memo,folderName(),i.photos.map(p=>p.name).join(" / "),i.x.toFixed(4),i.y.toFixed(4)]));download(new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n")],{type:"text/csv"}),safe($("bridge").value||"bridge")+"_野帳.csv")};$("jsonBtn").onclick=()=>download(new Blob([JSON.stringify(data(),null,2)],{type:"application/json"}),safe($("bridge").value||"bridge")+"_保存データ.json");$("zipBtn").onclick=async()=>{if(typeof JSZip==="undefined")return alert("ZIP機能の読込に失敗しました");let z=new JSZip(),cnt=0;st.icons.forEach(i=>i.photos.forEach(p=>{z.file(p.name,p.src.split(",")[1],{base64:true});cnt++}));if(!cnt)return alert("写真がありません");download(await z.generateAsync({type:"blob"}),safe($("bridge").value||"bridge")+"_写真.zip")};function download(blob,name){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click()}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("thumbBtn").onclick=async()=>{if(!st.pdf)return alert("PDFを先に読み込んでください");$("thumbModal").classList.remove("hidden");await buildThumbs()};$("closeThumb").onclick=()=>$("thumbModal").classList.add("hidden");async function buildThumbs(){let g=$("thumbGrid");g.innerHTML="";for(let n=1;n<=st.pages;n++){let card=document.createElement("div");card.className="pageCard"+(st.checked[n]?" checked":"");card.innerHTML=`<div class="pageNo">${n}ページ</div><canvas></canvas><label><input type="checkbox" ${st.checked[n]?"checked":""}>チェック済みにする</label>`;g.appendChild(card);let page=await st.pdf.getPage(n),vp=page.getViewport({scale:.22}),cv=card.querySelector("canvas");cv.width=vp.width;cv.height=vp.height;await page.render({canvasContext:cv.getContext("2d"),viewport:vp}).promise;card.querySelector("input").onchange=e=>{st.checked[n]=e.target.checked;card.classList.toggle("checked",e.target.checked);updatePageBadge();save()};cv.onclick=async()=>{$("thumbModal").classList.add("hidden");await goPage(n)}}}
$("oneDriveBtn").onclick=async()=>{let photos=[];st.icons.forEach(i=>i.photos.forEach(p=>photos.push(p)));if(!photos.length)return alert("保存する写真がありません。");let clientId=$("clientId").value.trim();if(!clientId)return alert("Microsoft Client IDが未設定です。会社のMicrosoft 365管理者にアプリ登録を依頼してください。");try{const app=new msal.PublicClientApplication({auth:{clientId,authority:"https://login.microsoftonline.com/common",redirectUri:location.href.split("#")[0]}});let login=await app.loginPopup({scopes:["Files.ReadWrite"]});let token=await app.acquireTokenSilent({account:login.account,scopes:["Files.ReadWrite"]}).catch(()=>app.acquireTokenPopup({scopes:["Files.ReadWrite"]}));for(const p of photos){let blob=dataUrlToBlob(p.src);let path=`/${encodeURIComponent(folderName())}/${encodeURIComponent(p.name)}:/content`;await fetch("https://graph.microsoft.com/v1.0/me/drive/root:"+path,{method:"PUT",headers:{Authorization:"Bearer "+token.accessToken,"Content-Type":"image/jpeg"},body:blob})}alert(`OneDriveの「${folderName()}」フォルダへ ${photos.length}枚 保存しました。`)}catch(e){alert("OneDrive保存に失敗しました: "+(e.message||e))}};function dataUrlToBlob(dataUrl){let b64=dataUrl.split(",")[1],bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:"image/jpeg"})}
try{let d=JSON.parse(localStorage.getItem("fieldbook_v6")||"{}");if(d.v){$("bridge").value=d.bridge||"";$("route").value=d.route||"";$("date").value=d.date||$("date").value;$("person").value=d.person||"";$("folder").value=d.folder||"";$("clientId").value=d.clientId||"";st.icons=d.icons||[];st.draw=d.draw||[];st.texts=d.texts||[];st.checked=d.checked||{};st.appZoom=d.appZoom||1;st.photoSeq=d.photoSeq||1;$("appMain").style.transform=`scale(${st.appZoom})`}}catch(e){}list();